# Generated by Django 4.0.4 on 2022-05-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pointBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posterName', models.CharField(max_length=15)),
                ('coordinate', models.CharField(max_length=60)),
                ('situation', models.IntegerField()),
                ('remark', models.TextField(max_length=150)),
                ('popularNum', models.IntegerField()),
                ('picLink', models.CharField(max_length=100)),
                ('isSlove', models.BooleanField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
    ]
