# Generated by Django 3.2.8 on 2022-05-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeMap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HELLOBOX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='pointbox',
            name='endDate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pointbox',
            name='isSlove',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pointbox',
            name='startDate',
            field=models.CharField(max_length=10),
        ),
    ]
