# Generated by Django 4.0.5 on 2022-06-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeMap', '0002_auto_20220530_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointbox',
            name='situaName',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pointbox',
            name='endDate',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pointbox',
            name='isSlove',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointbox',
            name='picLink',
            field=models.CharField(default='NOT_YET', max_length=100),
        ),
        migrations.AlterField(
            model_name='pointbox',
            name='popularNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointbox',
            name='posterName',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pointbox',
            name='startDate',
            field=models.CharField(max_length=40),
        ),
    ]
