# Generated by Django 4.0.5 on 2022-06-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeMap', '0003_pointbox_situaname_alter_pointbox_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointbox',
            name='picLink',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
