# Generated by Django 4.0.6 on 2022-08-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeMap', '0004_alter_pointbox_piclink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointbox',
            name='picLink',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
