# Generated by Django 4.0.6 on 2022-09-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeMap', '0005_alter_pointbox_piclink'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointbox',
            name='physicalAddr',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
