# Generated by Django 4.0.6 on 2022-09-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeMap', '0006_pointbox_physicaladdr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointbox',
            name='physicalAddr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pointbox',
            name='remark',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
